# Generated by Django 2.2.5 on 2019-09-30 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('pages', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_edit', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('percent_corrected', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.Project')),
                ('title_statement', models.CharField(default=None, max_length=255, null=True)),
                ('edition_statement', models.CharField(default=None, max_length=255, null=True)),
                ('notes_statement', models.CharField(default=None, max_length=255, null=True)),
                ('publication_statement', models.CharField(default=None, max_length=255, null=True)),
                ('series_statement', models.CharField(default=None, max_length=255, null=True)),
                ('source_description', models.CharField(default=None, max_length=255, null=True)),
                ('extent', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
