# Generated by Django 2.2.5 on 2019-09-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreRule',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('ignore', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleRule',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('base', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
            ],
        ),
    ]
